### ISSUE TITLE
smolok-cmd:0.0.2-SNAPSHOT not starting

### ISSUE THREAD

**Issue by ajurasz** [smolok/smolok#91]
I think this is a better place for this issue. 

After update of Dockerfiles [1], there is still following issue:

```
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newMpscQueue()Ljava/util/Queue;
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:168)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:146)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:33)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:115)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:125)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:114)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:110)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
	at io.vertx.core.Vertx.vertx(Vertx.java:79)
	at io.vertx.core.Vertx$vertx.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at smolok.lib.vertx.spring.VertxConfiguration.vertx(VertxConfiguration.groovy:13)
	at smolok.lib.vertx.spring.VertxConfiguration$$EnhancerBySpringCGLIB$$d0cd0a99.CGLIB$vertx$5(<generated>)
	at smolok.lib.vertx.spring.VertxConfiguration$$EnhancerBySpringCGLIB$$d0cd0a99$$FastClassBySpringCGLIB$$8de17072.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at smolok.lib.vertx.spring.VertxConfiguration$$EnhancerBySpringCGLIB$$d0cd0a99.vertx(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 105 more
```

Update didn't help because version of netty (vertx) didn't change between versions `0.0.1` and `0.0.2-SNAPSHOT`. It seems that we have got incorect version of netty on classpath, but not sure were it came from ...

[1] - 08640a596b1aa16250456829b9aaaf1f762ec631

**Comment by ajurasz** [comment]
At this point everyting was fine [1]

[1] - f38dafea56c0bdc493e5319dc2df6f0637fac0de

**Comment by hekonsek** [comment]
I think I have nailed it. Give me moment... :)

**Comment by ajurasz** [comment]
Well upgrade to Spring Boot 1.4 - 4f9c2b275d3656784d713d6486b408412b9eb989

**Comment by hekonsek** [comment]
Fixed. The problem was with Camel 2.17 pulling wrong version of netty-all which conflicted with version used by Vert.x.

**Comment by hekonsek** [comment]
Pushed fixed 0.0.2-SNAPSHOT cmd image to DockerHub, so feel free to give it a try.

**Comment by ajurasz** [comment]
Confirm, issue fixed. Thx.

**Comment by hekonsek** [comment]
BTW I have just released Smolok 0.0.2, so you can safely use it to avoid SNAPSHOTs.

**Comment by ajurasz** [comment]
Reopen to upgrate to 0.0.2.

**Comment by ajurasz** [comment]
Done, we are now using 0.0.2
